# Generated by Django 5.1 on 2024-08-13 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familiya', models.CharField(max_length=100, null=True)),
                ('lavozimi', models.CharField(max_length=100, null=True)),
                ('bolim', models.CharField(max_length=100, null=True)),
                ('telefon_raqami', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boshlash_vaqti', models.DateTimeField(auto_now_add=True)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='davomatapp.xodim')),
            ],
        ),
    ]
